# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'user_interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(881, 593)
        MainWindow.setStyleSheet("QWidget {\n"
"    \n"
"    background-color: rgb(245, 245, 245);\n"
"}\n"
"  \n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QWidget {\n"
"background-color: rgb(106, 106, 106);\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.Face = QtWidgets.QLabel(self.centralwidget)
        self.Face.setGeometry(QtCore.QRect(480, 480, 341, 141))
        font = QtGui.QFont()
        font.setPointSize(72)
        self.Face.setFont(font)
        self.Face.setStyleSheet("QLabel {\n"
"    background-color: none;\n"
"    border: none; \n"
"}")
        self.Face.setText("")
        self.Face.setAlignment(QtCore.Qt.AlignCenter)
        self.Face.setObjectName("Face")
        self.Tab = QtWidgets.QTabWidget(self.centralwidget)
        self.Tab.setGeometry(QtCore.QRect(0, 20, 881, 571))
        self.Tab.setTabletTracking(False)
        self.Tab.setAcceptDrops(False)
        self.Tab.setAutoFillBackground(False)
        self.Tab.setStyleSheet("QTabBar::tab { \n"
"height: 20px; \n"
"width: 80px;\n"
"background-color: rgb(227, 227, 227);\n"
"border-top-right-radius : 5px;\n"
"border-top-left-radius : 5px;\n"
"\n"
"}\n"
"\n"
"QTabWidget::pane {\n"
"border: 0px;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"background-color: rgb(120, 169, 202);\n"
"}\n"
"\n"
"QTabBar::tab:hover {\n"
"background-color: rgb(48, 96, 144);\n"
"}")
        self.Tab.setTabPosition(QtWidgets.QTabWidget.North)
        self.Tab.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.Tab.setIconSize(QtCore.QSize(32, 32))
        self.Tab.setElideMode(QtCore.Qt.ElideLeft)
        self.Tab.setDocumentMode(True)
        self.Tab.setTabsClosable(False)
        self.Tab.setMovable(False)
        self.Tab.setTabBarAutoHide(False)
        self.Tab.setObjectName("Tab")
        self.Setting = QtWidgets.QWidget()
        self.Setting.setStyleSheet("QWidget {\n"
"background-color: rgb(120, 169, 202);\n"
"}")
        self.Setting.setObjectName("Setting")
        self.Source = QtWidgets.QGroupBox(self.Setting)
        self.Source.setGeometry(QtCore.QRect(10, 10, 471, 151))
        self.Source.setStyleSheet("QGroupBox#Source{\n"
"    background-color: #f2f2f2;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"}\n"
"  \n"
"")
        self.Source.setTitle("")
        self.Source.setObjectName("Source")
        self.Browser = QtWidgets.QPushButton(self.Source)
        self.Browser.setGeometry(QtCore.QRect(10, 50, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Browser.setFont(font)
        self.Browser.setStyleSheet("QPushButton#Browser:hover:!pressed\n"
"{\n"
"      \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 15, 43, 255), stop:1 rgba(36, 115, 173, 255));\n"
"}\n"
"QPushButton#Browser {\n"
"    \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(46, 106, 147, 255), stop:1 rgba(50, 169, 255, 255));\n"
"    border: none; \n"
"    color: white;\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton#Browser:disabled {\n"
"     background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 15, 43, 255), stop:1 rgba(36, 115, 173, 255));\n"
"}")
        self.Browser.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("static/icon/folder-open-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Browser.setIcon(icon)
        self.Browser.setIconSize(QtCore.QSize(24, 24))
        self.Browser.setObjectName("Browser")
        self.Filename = QtWidgets.QLabel(self.Source)
        self.Filename.setGeometry(QtCore.QRect(10, 50, 441, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(9)
        self.Filename.setFont(font)
        self.Filename.setStyleSheet("QLabel#Filename {\n"
"      background-color: #bfbfbf;\n"
"      border: none; \n"
"    color: white;\n"
"    border-radius: 20px;\n"
"}")
        self.Filename.setScaledContents(False)
        self.Filename.setWordWrap(False)
        self.Filename.setIndent(50)
        self.Filename.setObjectName("Filename")
        self.Title = QtWidgets.QLabel(self.Source)
        self.Title.setGeometry(QtCore.QRect(-20, 0, 131, 31))
        self.Title.setStyleSheet("QLabel#Title {\n"
"    background-color: rgb(90, 90, 90);\n"
"    border: none; \n"
"    border-bottom-right-radius : 15px;\n"
"}")
        self.Title.setText("")
        self.Title.setObjectName("Title")
        self.Name = QtWidgets.QLabel(self.Source)
        self.Name.setGeometry(QtCore.QRect(10, 5, 91, 20))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Name.setFont(font)
        self.Name.setStyleSheet("QLabel#Name {\n"
"    background-color: none;\n"
"    color: white;\n"
"    border: none; \n"
"    border-radius: 8px;\n"
"}\n"
"")
        self.Name.setObjectName("Name")
        self.Filename.raise_()
        self.Browser.raise_()
        self.Title.raise_()
        self.Name.raise_()
        self.Save = QtWidgets.QGroupBox(self.Setting)
        self.Save.setGeometry(QtCore.QRect(10, 170, 471, 181))
        self.Save.setStyleSheet("QGroupBox#Save{\n"
"    background-color: #f2f2f2;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"}\n"
"  \n"
"")
        self.Save.setTitle("")
        self.Save.setObjectName("Save")
        self.Filename_2 = QtWidgets.QLabel(self.Save)
        self.Filename_2.setGeometry(QtCore.QRect(10, 50, 441, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(9)
        self.Filename_2.setFont(font)
        self.Filename_2.setStyleSheet("QLabel#Filename_2 {\n"
"      background-color: #bfbfbf;\n"
"      border: none; \n"
"    color: white;\n"
"    border-radius: 20px;\n"
"}")
        self.Filename_2.setScaledContents(False)
        self.Filename_2.setWordWrap(False)
        self.Filename_2.setIndent(50)
        self.Filename_2.setObjectName("Filename_2")
        self.Browser_2 = QtWidgets.QPushButton(self.Save)
        self.Browser_2.setGeometry(QtCore.QRect(10, 50, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Browser_2.setFont(font)
        self.Browser_2.setStyleSheet("QPushButton#Browser_2:hover:!pressed\n"
"{\n"
"      \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 15, 43, 255), stop:1 rgba(36, 115, 173, 255));\n"
"}\n"
"QPushButton#Browser_2 {\n"
"    \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(46, 106, 147, 255), stop:1 rgba(50, 169, 255, 255));\n"
"    border: none; \n"
"    color: white;\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton#Browser_2:disabled {\n"
"     background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 15, 43, 255), stop:1 rgba(36, 115, 173, 255));\n"
"}")
        self.Browser_2.setText("")
        self.Browser_2.setIcon(icon)
        self.Browser_2.setIconSize(QtCore.QSize(24, 24))
        self.Browser_2.setObjectName("Browser_2")
        self.Title_2 = QtWidgets.QLabel(self.Save)
        self.Title_2.setGeometry(QtCore.QRect(0, 0, 111, 31))
        self.Title_2.setStyleSheet("QLabel#Title_2 {\n"
"    background-color: rgb(90, 90, 90);\n"
"    border: none; \n"
"    border-bottom-right-radius : 15px;\n"
"}")
        self.Title_2.setText("")
        self.Title_2.setObjectName("Title_2")
        self.Name_2 = QtWidgets.QLabel(self.Save)
        self.Name_2.setGeometry(QtCore.QRect(10, 5, 91, 20))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Name_2.setFont(font)
        self.Name_2.setStyleSheet("QLabel#Name_2 {\n"
"    background-color: none;\n"
"    color: white;\n"
"    border: none; \n"
"    border-radius: 8px;\n"
"}\n"
"")
        self.Name_2.setObjectName("Name_2")
        self.Result_dir = QtWidgets.QLabel(self.Save)
        self.Result_dir.setGeometry(QtCore.QRect(20, 120, 311, 51))
        self.Result_dir.setStyleSheet("QLabel#Result_dir {\n"
"      background-color: none;\n"
"      border: none; \n"
"    color: black;\n"
"}")
        self.Result_dir.setText("")
        self.Result_dir.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.Result_dir.setObjectName("Result_dir")
        self.Copy_Right = QtWidgets.QLabel(self.Setting)
        self.Copy_Right.setGeometry(QtCore.QRect(10, 520, 211, 21))
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        self.Copy_Right.setFont(font)
        self.Copy_Right.setStyleSheet("QLabel {\n"
"    \n"
"    background-color: rgb(120, 169, 202);\n"
"}")
        self.Copy_Right.setObjectName("Copy_Right")
        self.Total = QtWidgets.QGroupBox(self.Setting)
        self.Total.setGeometry(QtCore.QRect(500, 10, 371, 291))
        self.Total.setStyleSheet("QGroupBox#Total{\n"
"    background-color: #f2f2f2;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"}\n"
"  \n"
"")
        self.Total.setTitle("")
        self.Total.setObjectName("Total")
        self.Tcounter = QtWidgets.QLabel(self.Total)
        self.Tcounter.setGeometry(QtCore.QRect(20, 20, 331, 251))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(12)
        self.Tcounter.setFont(font)
        self.Tcounter.setStyleSheet("QLabel#Tcounter {\n"
"      background-color: none;\n"
"      border: none; \n"
"    color: black;\n"
"}")
        self.Tcounter.setTextFormat(QtCore.Qt.RichText)
        self.Tcounter.setScaledContents(False)
        self.Tcounter.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.Tcounter.setWordWrap(True)
        self.Tcounter.setIndent(0)
        self.Tcounter.setObjectName("Tcounter")
        self.Violation = QtWidgets.QGroupBox(self.Setting)
        self.Violation.setGeometry(QtCore.QRect(500, 310, 371, 201))
        self.Violation.setStyleSheet("QGroupBox#Violation{\n"
"    background-color: #f2f2f2;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"}\n"
"  \n"
"")
        self.Violation.setTitle("")
        self.Violation.setObjectName("Violation")
        self.Vcounter = QtWidgets.QLabel(self.Violation)
        self.Vcounter.setGeometry(QtCore.QRect(20, 20, 321, 161))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(12)
        self.Vcounter.setFont(font)
        self.Vcounter.setStyleSheet("QLabel#Vcounter {\n"
"      background-color: none;\n"
"      border: none; \n"
"    color: black;\n"
"}")
        self.Vcounter.setTextFormat(QtCore.Qt.RichText)
        self.Vcounter.setScaledContents(False)
        self.Vcounter.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.Vcounter.setWordWrap(False)
        self.Vcounter.setIndent(0)
        self.Vcounter.setObjectName("Vcounter")
        self.Display = QtWidgets.QGroupBox(self.Setting)
        self.Display.setGeometry(QtCore.QRect(10, 360, 471, 151))
        self.Display.setStyleSheet("QGroupBox#Display{\n"
"    background-color: #f2f2f2;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"}\n"
"  \n"
"")
        self.Display.setTitle("")
        self.Display.setObjectName("Display")
        self.Title_3 = QtWidgets.QLabel(self.Display)
        self.Title_3.setGeometry(QtCore.QRect(0, 0, 121, 31))
        self.Title_3.setStyleSheet("QLabel#Title_3 {\n"
"    background-color: rgb(90, 90, 90);\n"
"    border: none; \n"
"    border-bottom-right-radius : 15px;\n"
"}")
        self.Title_3.setText("")
        self.Title_3.setObjectName("Title_3")
        self.Name_3 = QtWidgets.QLabel(self.Display)
        self.Name_3.setGeometry(QtCore.QRect(10, 5, 101, 20))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Name_3.setFont(font)
        self.Name_3.setStyleSheet("QLabel#Name_3 {\n"
"    background-color: none;\n"
"    color: white;\n"
"    border: none; \n"
"    border-radius: 8px;\n"
"}\n"
"")
        self.Name_3.setObjectName("Name_3")
        self.ShowLabel = QtWidgets.QCheckBox(self.Display)
        self.ShowLabel.setGeometry(QtCore.QRect(10, 60, 201, 21))
        self.ShowLabel.setStyleSheet("QCheckBox {\n"
"background-color: None;\n"
"}")
        self.ShowLabel.setChecked(True)
        self.ShowLabel.setObjectName("ShowLabel")
        self.ShowBox = QtWidgets.QCheckBox(self.Display)
        self.ShowBox.setGeometry(QtCore.QRect(10, 90, 201, 21))
        self.ShowBox.setStyleSheet("QCheckBox {\n"
"background-color: None;\n"
"}")
        self.ShowBox.setObjectName("ShowBox")
        self.SaveImage = QtWidgets.QCheckBox(self.Display)
        self.SaveImage.setGeometry(QtCore.QRect(250, 60, 211, 21))
        self.SaveImage.setStyleSheet("QCheckBox {\n"
"background-color: None;\n"
"}")
        self.SaveImage.setChecked(True)
        self.SaveImage.setObjectName("SaveImage")
        self.SaveVideo = QtWidgets.QCheckBox(self.Display)
        self.SaveVideo.setGeometry(QtCore.QRect(250, 90, 211, 21))
        self.SaveVideo.setStyleSheet("QCheckBox {\n"
"background-color: None;\n"
"}")
        self.SaveVideo.setChecked(True)
        self.SaveVideo.setObjectName("SaveVideo")
        self.line = QtWidgets.QFrame(self.Setting)
        self.line.setGeometry(QtCore.QRect(482, 10, 16, 501))
        self.line.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line.setMidLineWidth(0)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setObjectName("line")
        self.Tab.addTab(self.Setting, "")
        self.Draw = QtWidgets.QWidget()
        self.Draw.setStyleSheet("QWidget {\n"
"background-color: rgb(120, 169, 202);\n"
"}")
        self.Draw.setObjectName("Draw")
        self.Line = QtWidgets.QPushButton(self.Draw)
        self.Line.setGeometry(QtCore.QRect(10, 500, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Poppins SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Line.setFont(font)
        self.Line.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Line.setStyleSheet("QPushButton#Line:disabled {\n"
"     background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0.273, stop:0.0170455 rgba(118, 0, 0, 255), stop:0.727273 rgba(61, 0, 0, 255));\n"
"}\n"
"QPushButton#Line:hover:!pressed {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 15, 43, 255), stop:1 rgba(36, 115, 173, 255));\n"
"}\n"
"QPushButton#Line {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(46, 106, 147, 255), stop:1 rgba(50, 169, 255, 255));\n"
"    border: none; \n"
"    color: white;\n"
"    border-radius: 20px;\n"
"}\n"
"")
        self.Line.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("static/icon/line-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Line.setIcon(icon1)
        self.Line.setIconSize(QtCore.QSize(24, 24))
        self.Line.setAutoRepeat(False)
        self.Line.setAutoExclusive(False)
        self.Line.setFlat(False)
        self.Line.setObjectName("Line")
        self.Square = QtWidgets.QPushButton(self.Draw)
        self.Square.setGeometry(QtCore.QRect(70, 500, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Poppins SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Square.setFont(font)
        self.Square.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Square.setStyleSheet("QPushButton#Square:disabled {\n"
"     background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0.273, stop:0.0170455 rgba(118, 0, 0, 255), stop:0.727273 rgba(61, 0, 0, 255));\n"
"}\n"
"QPushButton#Square:hover:!pressed {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 15, 43, 255), stop:1 rgba(36, 115, 173, 255));\n"
"}\n"
"QPushButton#Square {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(46, 106, 147, 255), stop:1 rgba(50, 169, 255, 255));\n"
"    border: none; \n"
"    color: white;\n"
"    border-radius: 20px;\n"
"}\n"
"")
        self.Square.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("static/icon/crect-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Square.setIcon(icon2)
        self.Square.setIconSize(QtCore.QSize(24, 24))
        self.Square.setAutoRepeat(False)
        self.Square.setAutoExclusive(False)
        self.Square.setFlat(False)
        self.Square.setObjectName("Square")
        self.Draw_line = QtWidgets.QWidget(self.Draw)
        self.Draw_line.setGeometry(QtCore.QRect(10, 10, 854, 480))
        self.Draw_line.setStyleSheet("QWidget {\n"
"        background-color: rgb(62, 62, 62);\n"
"}")
        self.Draw_line.setObjectName("Draw_line")
        self.Delete = QtWidgets.QPushButton(self.Draw)
        self.Delete.setGeometry(QtCore.QRect(130, 500, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Poppins SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Delete.setFont(font)
        self.Delete.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Delete.setStyleSheet("QPushButton#Delete:disabled {\n"
"     background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0.273, stop:0.0170455 rgba(118, 0, 0, 255), stop:0.727273 rgba(61, 0, 0, 255));\n"
"}\n"
"QPushButton#Delete:hover:!pressed {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 15, 43, 255), stop:1 rgba(36, 115, 173, 255));\n"
"}\n"
"QPushButton#Delete {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(46, 106, 147, 255), stop:1 rgba(50, 169, 255, 255));\n"
"    border: none; \n"
"    color: white;\n"
"    border-radius: 20px;\n"
"}\n"
"")
        self.Delete.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("static/icon/back-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Delete.setIcon(icon3)
        self.Delete.setIconSize(QtCore.QSize(24, 24))
        self.Delete.setAutoRepeat(False)
        self.Delete.setAutoExclusive(False)
        self.Delete.setFlat(False)
        self.Delete.setObjectName("Delete")
        self.Tab.addTab(self.Draw, "")
        self.Monitor = QtWidgets.QWidget()
        self.Monitor.setStyleSheet("QWidget {\n"
"background-color: rgb(120, 169, 202);\n"
"}")
        self.Monitor.setObjectName("Monitor")
        self.Play = QtWidgets.QPushButton(self.Monitor)
        self.Play.setGeometry(QtCore.QRect(10, 500, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Poppins SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Play.setFont(font)
        self.Play.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Play.setStyleSheet("QPushButton#Play:disabled {\n"
"     background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0.273, stop:0.0170455 rgba(118, 0, 0, 255), stop:0.727273 rgba(61, 0, 0, 255));\n"
"}\n"
"QPushButton#Play:hover:!pressed {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 15, 43, 255), stop:1 rgba(36, 115, 173, 255));\n"
"}\n"
"QPushButton#Play {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(46, 106, 147, 255), stop:1 rgba(50, 169, 255, 255));\n"
"    border: none; \n"
"    color: white;\n"
"    border-radius: 20px;\n"
"}\n"
"")
        self.Play.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("static/icon/play-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Play.setIcon(icon4)
        self.Play.setIconSize(QtCore.QSize(16, 16))
        self.Play.setAutoRepeat(False)
        self.Play.setAutoExclusive(False)
        self.Play.setFlat(False)
        self.Play.setObjectName("Play")
        self.Stop = QtWidgets.QPushButton(self.Monitor)
        self.Stop.setGeometry(QtCore.QRect(70, 500, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Poppins SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Stop.setFont(font)
        self.Stop.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Stop.setStyleSheet("QPushButton#Stop:disabled {\n"
"     background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0.273, stop:0.0170455 rgba(118, 0, 0, 255), stop:0.727273 rgba(61, 0, 0, 255));\n"
"}\n"
"QPushButton#Stop:hover:!pressed {\n"
"    \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(36, 11, 11, 255), stop:1 rgba(255, 50, 119, 255));\n"
"}\n"
"QPushButton#Stop {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(147, 46, 46, 255), stop:1 rgba(255, 50, 119, 255));\n"
"    border: none; \n"
"    color: white;\n"
"    border-radius: 20px;\n"
"}\n"
"")
        self.Stop.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("static/icon/stop-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Stop.setIcon(icon5)
        self.Stop.setIconSize(QtCore.QSize(16, 16))
        self.Stop.setAutoRepeat(False)
        self.Stop.setAutoExclusive(False)
        self.Stop.setFlat(False)
        self.Stop.setObjectName("Stop")
        self.Camera_view = QtWidgets.QWidget(self.Monitor)
        self.Camera_view.setGeometry(QtCore.QRect(10, 10, 854, 480))
        self.Camera_view.setStyleSheet("QWidget {\n"
"    background-color: rgb(62, 62, 62);\n"
"}")
        self.Camera_view.setObjectName("Camera_view")
        self.Tab.addTab(self.Monitor, "")
        self.Export = QtWidgets.QWidget()
        self.Export.setStyleSheet("QWidget {\n"
"background-color: rgb(120, 169, 202);\n"
"}")
        self.Export.setObjectName("Export")
        self.Save_video = QtWidgets.QPushButton(self.Export)
        self.Save_video.setGeometry(QtCore.QRect(10, 500, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Save_video.setFont(font)
        self.Save_video.setStyleSheet("QPushButton#Save_video:hover:!pressed\n"
"{\n"
"      \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 15, 43, 255), stop:1 rgba(36, 115, 173, 255));\n"
"}\n"
"QPushButton#Save_video {\n"
"    \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(46, 106, 147, 255), stop:1 rgba(50, 169, 255, 255));\n"
"    border: none; \n"
"    color: white;\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton#Save_video:disabled {\n"
"     background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 15, 43, 255), stop:1 rgba(36, 115, 173, 255));\n"
"}")
        self.Save_video.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("static/icon/save-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Save_video.setIcon(icon6)
        self.Save_video.setIconSize(QtCore.QSize(24, 24))
        self.Save_video.setObjectName("Save_video")
        self.Table = QtWidgets.QTableWidget(self.Export)
        self.Table.setGeometry(QtCore.QRect(10, 10, 291, 481))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Table.sizePolicy().hasHeightForWidth())
        self.Table.setSizePolicy(sizePolicy)
        self.Table.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Table.setStyleSheet("QTableWidget {\n"
"    background-color: #f2f2f2;\n"
"    border: 2px solid gray;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    color: black;\n"
"    padding-top: 6px;\n"
"}\n"
"\n"
"QHeaderView {\n"
"    qproperty-defaultAlignment: AlignHCenter;\n"
"}\n"
"")
        self.Table.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.Table.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Table.setLineWidth(1)
        self.Table.setMidLineWidth(1)
        self.Table.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.Table.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.Table.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.SelectedClicked)
        self.Table.setDefaultDropAction(QtCore.Qt.IgnoreAction)
        self.Table.setAlternatingRowColors(True)
        self.Table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.Table.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.Table.setGridStyle(QtCore.Qt.SolidLine)
        self.Table.setWordWrap(True)
        self.Table.setRowCount(0)
        self.Table.setColumnCount(1)
        self.Table.setObjectName("Table")
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.Table.setHorizontalHeaderItem(0, item)
        self.Table.horizontalHeader().setCascadingSectionResizes(False)
        self.Table.horizontalHeader().setDefaultSectionSize(140)
        self.Table.horizontalHeader().setMinimumSectionSize(40)
        self.Table.horizontalHeader().setStretchLastSection(True)
        self.Table.verticalHeader().setVisible(False)
        self.Table.verticalHeader().setDefaultSectionSize(40)
        self.Table.verticalHeader().setHighlightSections(True)
        self.Table.verticalHeader().setMinimumSectionSize(40)
        self.Table.verticalHeader().setSortIndicatorShown(False)
        self.Table.verticalHeader().setStretchLastSection(False)
        self.Export_view = QtWidgets.QGroupBox(self.Export)
        self.Export_view.setGeometry(QtCore.QRect(310, 10, 561, 481))
        self.Export_view.setStyleSheet("QGroupBox#Export_view{\n"
"    background-color: #f2f2f2;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"}\n"
"  \n"
"")
        self.Export_view.setTitle("")
        self.Export_view.setObjectName("Export_view")
        self.Preview = QtWidgets.QLabel(self.Export_view)
        self.Preview.setGeometry(QtCore.QRect(0, 60, 561, 361))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(1)
        self.Preview.setFont(font)
        self.Preview.setStyleSheet("QLabel#Preview {\n"
"    color: white;\n"
"    background-color: none;\n"
"}")
        self.Preview.setText("")
        self.Preview.setAlignment(QtCore.Qt.AlignCenter)
        self.Preview.setObjectName("Preview")
        self.Preview_name = QtWidgets.QLabel(self.Export_view)
        self.Preview_name.setGeometry(QtCore.QRect(20, 10, 221, 21))
        self.Preview_name.setStyleSheet("QLabel#Preview_name {\n"
"      background-color: none;\n"
"      border: none; \n"
"    color: black;\n"
"}")
        self.Preview_name.setObjectName("Preview_name")
        self.Tab.addTab(self.Export, "")
        self.blank = QtWidgets.QLabel(self.centralwidget)
        self.blank.setGeometry(QtCore.QRect(0, 0, 881, 21))
        self.blank.setStyleSheet("QLabel {\n"
"background-color: rgb(90, 90, 90);\n"
"}")
        self.blank.setText("")
        self.blank.setObjectName("blank")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(770, 5, 101, 31))
        self.groupBox.setStyleSheet("QGroupBox {\n"
"    background-color: rgb(45, 45, 45);\n"
"    border: none;\n"
"    border-radius: 15px;\n"
"}")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.Close = QtWidgets.QPushButton(self.groupBox)
        self.Close.setGeometry(QtCore.QRect(75, 5, 21, 21))
        self.Close.setStyleSheet("QPushButton#Close:hover:!pressed\n"
"{\n"
"      background-color: rgb(167, 30, 30);\n"
"}\n"
"QPushButton#Close {\n"
"    background-color: rgb(220, 60, 60);\n"
"    border: none; \n"
"    color: white;\n"
"    border-radius: 10px;\n"
"}\n"
"")
        self.Close.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("static/icon/times-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Close.setIcon(icon7)
        self.Close.setIconSize(QtCore.QSize(16, 16))
        self.Close.setObjectName("Close")
        self.Minimun = QtWidgets.QPushButton(self.groupBox)
        self.Minimun.setGeometry(QtCore.QRect(45, 5, 21, 21))
        self.Minimun.setStyleSheet("QPushButton#Minimun:hover:!pressed\n"
"{\n"
"      background-color: rgb(72, 72, 72);\n"
"}\n"
"QPushButton#Minimun {\n"
"    background-color: rgb(140, 140, 140);\n"
"    border: none; \n"
"    color: white;\n"
"    border-radius: 10px;\n"
"}\n"
"")
        self.Minimun.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("static/icon/minimum-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Minimun.setIcon(icon8)
        self.Minimun.setObjectName("Minimun")
        self.blank_2 = QtWidgets.QLabel(self.centralwidget)
        self.blank_2.setGeometry(QtCore.QRect(0, 588, 881, 4))
        self.blank_2.setStyleSheet("QLabel {\n"
"background-color: rgb(90, 90, 90);\n"
"}")
        self.blank_2.setText("")
        self.blank_2.setObjectName("blank_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.Tab.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Traffic Tracking System"))
        self.Filename.setText(_translate("MainWindow", "Browse your video here!"))
        self.Name.setText(_translate("MainWindow", "Video source"))
        self.Filename_2.setText(_translate("MainWindow", "Browse your saving folder here!"))
        self.Name_2.setText(_translate("MainWindow", "Result folder"))
        self.Copy_Right.setText(_translate("MainWindow", "© dev by Nguyen Trieu Phong"))
        self.Tcounter.setText(_translate("MainWindow", "Counter for the vehicles crossing the line"))
        self.Vcounter.setText(_translate("MainWindow", "Counter for the vehicles in violation"))
        self.Name_3.setText(_translate("MainWindow", "Display setting"))
        self.ShowLabel.setText(_translate("MainWindow", "Showing the detected label on video"))
        self.ShowBox.setText(_translate("MainWindow", "Showing the detected box on video"))
        self.SaveImage.setText(_translate("MainWindow", "Save image of the vehicle in violation"))
        self.SaveVideo.setText(_translate("MainWindow", "Save video of the vehicle in violation"))
        self.Tab.setTabText(self.Tab.indexOf(self.Setting), _translate("MainWindow", "Setting"))
        self.Tab.setTabText(self.Tab.indexOf(self.Draw), _translate("MainWindow", "Draw"))
        self.Tab.setTabText(self.Tab.indexOf(self.Monitor), _translate("MainWindow", "Home"))
        item = self.Table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        self.Preview_name.setText(_translate("MainWindow", "Double click each ID to show the image here!"))
        self.Tab.setTabText(self.Tab.indexOf(self.Export), _translate("MainWindow", "Export"))
